sudo : required
services : 
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_37b19f46013e_key -iv $encrypted_37b19f46013e_iv -in multi-k8s-tuyendo-091a32377af2.json.enc -out multi-k8s-tuyendo-091a32377af2.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
